[project]
name = "kawa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=3.3.1",
]

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest>=8.0",
    "ruff>=0.16.5",
]

[tool.pytest.ini_options]
pythonpath = ["."]
